# Header

menu:
  主页: /
  时间线: /archives/

# SubNav
subnav:
  github: "https://github.com/forienlauo"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  # douban: "#"
  # mail: "forienlauo@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 代码高亮 
highlight:
  enable: true
  auto_detect: true
  line_number: true
  # tab_replace: ''

# 使用google-prettify的代码高亮
prettify_highlight:
  enable: false
  theme: 'prettify.css'
  # theme: 'themes/tomorrow-night-bright.min.css'
# 需要跳过渲染
skip_render:
  - "static/js/google-code-prettify/**"

# 是否开启统计
# counter: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://oh4pp6966.bkt.clouddn.com/static/images/_common/avatar.jpg

#微信公众号二维码
weixin_qr_code: http://oh4pp6966.bkt.clouddn.com/static/images/_common/weixin_qr_code.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: true # 上线时开启
duoshuo: false # 本地测试时关闭

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: '关于我'

friends:
  Google大法好: https://google.com/
  # 友情链接2: http://localhost:4000/
  # 友情链接3: http://localhost:4000/
  # 友情链接4: http://localhost:4000/
  # 友情链接5: http://localhost:4000/
  # 友情链接6: http://localhost:4000/

aboutme: 这是一个技术博客集。<br>写下了一个蝼蚁之辈对计算机世界的敬畏。